=== ebourg/jetrix/src/etc/tetrinet-server.dtd
<!--
Jetrix TetriNET Server
Copyright (C) 2001-2002  Emmanuel Bourg

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License
as published by the Free Software Foundation; either version 2
of the License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
-->

<!-- JetriX configuration DTD ($Revision$, $Date$) -->

<!ENTITY % Block "(leftl | leftz | square | rightl | rightz | halfcross
  | line)*">
<!ENTITY % Special "(addline | clearline | nukefield | randomclear
  | switchfield | clearspecial | gravity | quakefield | blockbomb)*">
<!ENTITY % Ban "(host | nick | team)*">

<!ELEMENT tetrinet-server (name?, language?, timeout?, max-channels?,
  max-players?, max-connexions?, op-password, access-log, error-log, motd,
  filter-definitions?, default-filters?, default-settings, channels, commands, ban?)>
<!ATTLIST tetrinet-server host CDATA #IMPLIED>
<!ATTLIST tetrinet-server port CDATA #IMPLIED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT language (#PCDATA)>
<!ELEMENT timeout (#PCDATA)>
<!ELEMENT max-channels (#PCDATA)>
<!ELEMENT max-players (#PCDATA)>
<!ELEMENT max-connexions (#PCDATA)>
<!ELEMENT op-password (#PCDATA)>

<!ELEMENT access-log EMPTY>
<!ATTLIST access-log path CDATA #REQUIRED>

<!ELEMENT error-log EMPTY>
<!ATTLIST error-log path CDATA #REQUIRED>

<!ELEMENT motd (#PCDATA)>

<!ELEMENT filter-definitions (alias*)>
<!ELEMENT alias EMPTY>
<!ATTLIST alias name CDATA #REQUIRED>
<!ATTLIST alias class CDATA #REQUIRED>

<!ELEMENT default-filters (filter*)>
<!ELEMENT filter (param*)>
<!ATTLIST filter name CDATA #REQUIRED>
<!ELEMENT param EMPTY>
<!ATTLIST param name CDATA #REQUIRED>
<!ATTLIST param value CDATA #REQUIRED>

<!ELEMENT default-settings (starting-level, lines-per-level, level-increase,
  lines-per-special, special-added, special-capacity, classic-rules,
  average-levels, block-occurancy, special-occurancy)>
<!ELEMENT starting-level (#PCDATA)>
<!ELEMENT lines-per-level (#PCDATA)>
<!ELEMENT level-increase (#PCDATA)>
<!ELEMENT lines-per-special (#PCDATA)>
<!ELEMENT special-added (#PCDATA)>
<!ELEMENT special-capacity (#PCDATA)>
<!ELEMENT classic-rules (#PCDATA)>
<!ELEMENT average-levels (#PCDATA)>

<!ELEMENT block-occurancy %Block;>
<!ELEMENT leftl (#PCDATA)>
<!ELEMENT leftz (#PCDATA)>
<!ELEMENT square (#PCDATA)>
<!ELEMENT rightl (#PCDATA)>
<!ELEMENT rightz (#PCDATA)>
<!ELEMENT halfcross (#PCDATA)>
<!ELEMENT line (#PCDATA)>

<!ELEMENT special-occurancy %Special;>
<!ELEMENT addline (#PCDATA)>
<!ELEMENT clearline (#PCDATA)>
<!ELEMENT nukefield (#PCDATA)>
<!ELEMENT randomclear (#PCDATA)>
<!ELEMENT switchfield (#PCDATA)>
<!ELEMENT clearspecial (#PCDATA)>
<!ELEMENT gravity (#PCDATA)>
<!ELEMENT quakefield (#PCDATA)>
<!ELEMENT blockbomb (#PCDATA)>

<!ELEMENT channels (channel*)>
<!ELEMENT channel (description?, password?, access-level?, max-players?, settings?, class?, filters?)>
<!ATTLIST channel name CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT access-level (#PCDATA)>
<!ELEMENT settings (starting-level?, lines-per-level?, level-increase?,
  lines-per-special?, special-added?, special-capacity?, classic-rules?,
  average-levels?, block-occurancy?, special-occurancy?)>
<!ELEMENT class (#PCDATA)>
<!ELEMENT filters (filter)>

<!ELEMENT commands (command*)>
<!ELEMENT command (access-level?)>
<!ATTLIST command class CDATA #REQUIRED>

<!ELEMENT ban %Ban;>
<!ELEMENT host (#PCDATA)>
<!ELEMENT nick (#PCDATA)>
<!ELEMENT team (#PCDATA)>

=== ebourg/jetrix/src/etc/config.xml
<?xml version="1.0"?>
<!DOCTYPE tetrinet-server PUBLIC "-//LFJR//Jetrix TetriNET Server//EN" "http://jetrix.sourceforge.net/dtd/tetrinet-server.dtd">

<tetrinet-server host="[ALL]" port="31457">
  <name>JetriX TetriNET Server</name>
  
  <!-- Server language (using an ISO-639 two-letter language code) -->
  <language>en</language>

  <!-- How many seconds of no activity before timeout occurs -->
  <timeout>1000</timeout>

  <!-- How many channels should be available on server -->
  <max-channels>8</max-channels>

  <!-- Maximum number or players on server -->
  <max-players>50</max-players>

  <!-- Maximum number of simultaneous connexions allowed from the same IP -->
  <max-connexions>2</max-connexions>

  <!-- Typing /op <thispassword> will give player op status -->
  <op-password>jetrixpass</op-password>

  <!-- Access Log, where requests are logged to -->
  <access-log path="log/access%g.log" />

  <!-- Error Log, where errors are logged to -->
  <error-log  path="log/error%g.log" />

  <!-- Message Of The Day -->
  <motd>
Welcome on the experimental JetriX TetriNET Server !
http://jetrix.sourceforge.net/
------------------------------------------------
  </motd>
  
  <!-- Channel filters -->
  <filter-definitions>
    <alias name="flood" class="net.jetrix.filter.FloodFilter"/>
    <alias name="start" class="net.jetrix.filter.StartFilter"/>
    <alias name="amplifier" class="net.jetrix.filter.AmplifierFilter"/>
    <alias name="ping" class="net.jetrix.filter.PingFilter"/>
  </filter-definitions>

  <!-- Global filters -->
  <default-filters>
    <filter name="flood">
      <param name="capacity" value="8"/>
      <param name="delay" value="5000"/>
    </filter>
    <filter name="start">
      <param name="delay" value="10000"/>
    </filter>    
    <filter name="ping"/>
  </default-filters>

  <!-- Default game settings -->
  <default-settings>
    <!-- What level each player starts at -->
    <starting-level>1</starting-level>

    <!-- How many lines to make before player level increases -->
    <lines-per-level>2</lines-per-level>

    <!-- Number of levels to increase each time -->
    <level-increase>1</level-increase>

    <!-- Lines to make to get a special block -->
    <lines-per-special>2</lines-per-special>

    <!-- Number of special blocks added each time -->
    <special-added>1</special-added>

    <!-- Capacity of Special block inventory -->
    <special-capacity>18</special-capacity>

    <!-- Play by classic rules? -->
    <classic-rules>true</classic-rules>

    <!-- Average together all player's game level? -->
    <average-levels>true</average-levels>

    <block-occurancy>
      <leftl>14</leftl>
      <leftz>14</leftz>
      <square>15</square>
      <rightl>14</rightl>
      <rightz>14</rightz>
      <halfcross>14</halfcross>
      <line>15</line>
    </block-occurancy>

    <special-occurancy>
      <addline>32</addline>
      <clearline>18</clearline>
      <nukefield>1</nukefield>
      <randomclear>11</randomclear>
      <switchfield>3</switchfield>
      <clearspecial>14</clearspecial>
      <gravity>1</gravity>
      <quakefield>6</quakefield>
      <blockbomb>14</blockbomb>
    </special-occurancy>

  </default-settings>


  <channels>
    <channel name="welcome">
      <description>Welcome !</description>
    </channel>

    <channel name="welcome2">
      <description>Welcome !</description>
    </channel>

    <channel name="welcome3">
      <description>Welcome !</description>
    </channel>

    <channel name="pureduel">
      <description>Pure - No Specials</description>
      <max-players>2</max-players>
      <settings>
        <special-added>0</special-added>
      </settings>
    </channel>

    <channel name="sticks">
      <description>Sticks Only</description>
      <max-players>1</max-players>
      <settings>
        <special-added>0</special-added>
        <block-occurancy>
          <line>100</line>
        </block-occurancy>
      </settings>
    </channel>

    <channel name="SnS">
      <description>Sticks [i]and[/i] Squares</description>
      <settings>
        <special-added>0</special-added>
        <block-occurancy>
          <line>50</line>
          <square>50</square>
        </block-occurancy>
      </settings>
    </channel>

    <channel name="theatre">
      <description>The TetriNET Theatre</description>
      <class>org.lfjr.jetrix.channel.PlayBack</class>
    </channel>
    
    <channel name="laboratory">
      <description>Silly tests here</description>
      <filters>
        <filter name="amplifier"/>
      </filters>
    </channel>

    <channel name="private">
      <description>Protected channel</description>
      <password>sesame</password>
    </channel>

    <channel name="admins">
      <description>Administrators' Lair</description>
      <access-level>1</access-level>
    </channel>

  </channels>

  <!-- Server commands -->
  <commands>
    <command class="net.jetrix.commands.BroadcastCommand"/>
    <command class="net.jetrix.commands.ConfigCommand"/>
    <command class="net.jetrix.commands.EmoteCommand"/>
    <command class="net.jetrix.commands.HelpCommand"/>
    <command class="net.jetrix.commands.IpCommand"/>
    <command class="net.jetrix.commands.JoinCommand"/>
    <command class="net.jetrix.commands.KickCommand"/>
    <command class="net.jetrix.commands.LanguageCommand"/>
    <command class="net.jetrix.commands.ListCommand"/>
    <command class="net.jetrix.commands.MotdCommand"/>
    <command class="net.jetrix.commands.MoveCommand"/>
    <command class="net.jetrix.commands.OperatorCommand"/>
    <command class="net.jetrix.commands.PingCommand"/>
    <command class="net.jetrix.commands.SummonCommand"/>
    <command class="net.jetrix.commands.TeleportCommand"/>
    <command class="net.jetrix.commands.TellCommand"/>
    <command class="net.jetrix.commands.TimeCommand"/>
    <command class="net.jetrix.commands.VersionCommand"/>
    <command class="net.jetrix.commands.WhoCommand"/>
  </commands>

  <ban>
    <!-- Cheating from host 1cust007.tnt2.billgates.da.uu.net -->
    <host>*.tnt*.billgates.da.uu.net</host>

    <!-- Flooding from 192.168.33.200. Ban all C class IP block -->
    <host>192.168.33.*</host>

    <!-- Ban all hostname contain the word foobar -->
    <host>*foobar*</host>

    <!-- Ban IP block from 192.168.10.0 to 192.168.19.255 -->
    <host>192.168.1?.*</host>

    <!-- Ban nickname -->
    <nick>billgates</nick>

    <!-- Ban team -->
    <team>Flying Cucumbers</team>
  </ban>

</tetrinet-server>
